// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
import { initializeApp, getApp, getApps } from "firebase/app";

// Your web app's Firebase configuration
const firebaseConfig = {
  "projectId": "recipe-ace-78zcw",
  "appId": "1:792351340025:web:c7225e3b43c7905d39b928",
  "storageBucket": "recipe-ace-78zcw.firebasestorage.app",
  "apiKey": "AIzaSyDIoxCb27JgAAG8mJml-dy7BFqAs5zCiw8",
  "authDomain": "recipe-ace-78zcw.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "792351340025"
};

// Initialize Firebase
const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);

export { app };
